product = "Rage Fowls"
publisher = "donnaken15"
name = "Rage Fowls"
width = 1024
height = 768
orientation = 0
datapath = "data"
imagePath = "images"
fontPath = "fonts"
audioPath = "audio"
localizationPath = "localization"
levelPath = "levels"
scriptPath = "scripts"
commonScriptPath = "scripts_common"
shaderPath = "shaders"
deviceModel = "windows"
fullscreen = false
showCursor = true
singleton = false
renderer = { "gl2", "gl1" }
icon = 103
